// MOVIES
export const ADD_MOVIE = 'ADD_MOVIE';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const DELETE_MOVIE_START = 'DELETE_MOVIE_START';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_ERROR = 'DELETE_MOVIE_ERROR';

export const EDIT_MOVIE_START = 'EDIT_MOVIE_START';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const EDIT_MOVIE_ERROR = 'EDIT_MOVIE_ERROR';

export const NEW_MOVIE_START = 'NEW_MOVIE_START';
export const NEW_MOVIE_SUCCESS = 'NEW_MOVIE_SUCCESS';
export const NEW_MOVIE_ERROR = 'NEW_MOVIE_ERROR';

export const GET_MOVIE_START = 'GET_MOVIE_START';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';
